apiVersion: v1
kind: Pod
spec:
  containers:
    - name: azure-pyspark
      env:
      - name: SCONE_LAS_ADDR
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      resources:
        limits:
          cpu: "2"
          sgx.intel.com/enclave: 1
        requests:
          cpu: "1"
          sgx.intel.com/enclave: 1
