apiVersion: v1
kind: Pod
spec:
  containers:
    - name: azure-pyspark
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
          sgx.intel.com/enclave: 1
        requests:
          cpu: "1"
          memory: 2Gi
          sgx.intel.com/enclave: 1